### ISSUE TITLE
Ha aparecido este repositorio de la nada

### ISSUE THREAD

**Issue by alejandromyto** [KetpuntoG/Notebooks-del-canal#3]
En mi usuario de github alejandro-intergal ha aparecido este repositorio de la nada:
[Notebooks-del-canal]  Public Forked from [KetpuntoG/Notebooks-del-canal]
Updated on Aug 28, 2022.

¿Cómo ha sido posible?
Lo borro en cuanto me contestes, o mañana si no hay respuesta.

**Comment by KetpuntoG** [comment]
Buenas @alejandro-intergal , por mi parte no he hecho nada así que siéntete libre de eliminarlo 🙂
Saludos!
